### ISSUE TITLE
Project charter document

### ISSUE THREAD

**Issue by zzzamoraaa** [Giani2001/Proiect-IS#6]

**Comment by andreicontor** [comment]
# Project charter document

## Title : Music Player
## Project Manager: Contor Flavius-Andrei
## Project Team Members: Filote Serban, Zamora Teodor, Visalon Giani, Rotaru Radu
## Business Case: the application offers users a wide range of songs and playlists
## Project Benefits: 
- The user can create his own playlist with his favorite songs
- The user can search for the desired song in a very easy-to-use search bar
- Very welcoming and easy to use interface helps the user to pause and adjust the volume directly from the application
## Resources
- To do
## Starting Date
- To do
## Project completion Date
- To do
